/*อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                                                                              บ
บ  Generated by the DrDialog editor                                            บ
บ                                                                              บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/

#define MultiDeskMain    100
#define UsersContainer   203
#define ManageDeskBtn    206
#define SaveBtn          207
#define DiscardBtn       208
#define CtrlClose        211
#define CtrlMin          212
#define CtrlMaxRest      213
#define HintsBox         214
#define MsgBoxDlg        300
#define MessageText      303
#define NewUserBtn       304
#define TrashBtn         305
#define CtrlMove         306
#define InputValueDlg    400
#define MessageMLE       401
#define OKBtn            402
#define CancelBtn        403
#define InputField       404
#define LogDlg           500
#define LogList          501
#define HideBtn          502
#define IniSetupDlg      600
#define GroupsContainer  604
#define SUI_CopyBtn      605
#define SUI_ExitBtn      606
#define SUI_MoreBtn      607
#define SourceUserCBox   609
#define IniCopyDlg       700
#define SourceINIList    701
#define SourceUserBox    703
#define DestINIList      704
#define CopyEntryBtn     706
#define ICD_DoneBtn      708
#define RemoveEntryBtn   712
